### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Rochet2** [TheDuckFIN/Tsoha-Bootstrap#1]
Toivottavasti ebola ei ole vienyt :(
Kivat värit sivustolla.

Aika mukavasti tauluja ja testidataa. Ja aika täyteläs käyttötapauskaavio.
Tietokantatauluja kaavioissa aika monta, mutta käytännössä kaikki ei taida olla vielä tietokannassa, tai jos ovat, niin niistä ei vielä ole modeleita jos niitä edes tulee? Esim achievement puuttuu vielä.

indentaatiot tabeja D: Ihan hyvältä tuo koodi muuten näyttää ;)
Ei kannata muuten sitten kovakoodata niitä jormia lisää. :tangerine:

**Comment by lakaniemi** [comment]
ai onko ne muka tabeja ;_; pitää tsekkaa sublime textin asetuksii, oon kyl mielestäni säätäny ne spaceiks... Joo, kaikki on tosi WIP vielä, ja siks iso osa asioista puuttuu / on kesken :D
